### ISSUE TITLE
faceofpain gif download issue

### ISSUE THREAD

**Issue by imevilx** [aliparlakci/bulk-downloader-for-reddit#115]
i used python script /1.7.0 then 1.8.0 on windows 
faceofpain subreddit when I download top >all time
even first post is not getting downloaded tried everything
even when I try hot>only few posts are downloading others giving error
[WinError 10054] An existing connection was forcibly closed by the remote host
Trying again

**Comment by aliparlakci** [comment]
This is due redgifs and gfycat server. I cannot solve it. Soon there will be 1.9 release where you can skip certain post types and certain domains. After it is released, you can skip redgifs and gifdeliverynetwork links.

**Comment by parasiteoflife** [comment]
> This is due redgifs and gfycat server. I cannot solve it. Soon there will be 1.9 release where you can skip certain post types and certain domains. After it is released, you can skip redgifs and gifdeliverynetwork links.

Hey, I'm getting this a lot. This has been happening recently, before (before gfycat didn't allowed NSFW gifs and forced everyone on their redgifs site) I never got this error, and I've downloaded a LOT of files from gfycat so this came as a surprise, this error has been introduced recently?
How many connections does the program open with the servers? We could configure that to one and maybe that will solve this issue? Idk, it feels weird that before we could download fine from gfycat and now after updating the app from 1.5 to 1.9.1 I can't anymore because, as I said, the program have downloaded thousands of files from there without any kind of trouble.
