### ISSUE TITLE
Input via custom text file

### ISSUE THREAD

**Issue by anup2050** [aliparlakci/bulk-downloader-for-reddit#120]
can you add a feature where u can download in bulk through links in a text or csv file (one link in one line)

**Comment by anup2050** [comment]
also if it is possible can u add pushshift.io api with unix timestamp

**Comment by aliparlakci** [comment]
Open a new issue for this

**Comment by anup2050** [comment]
can it be done? if it can then thanks in advance.. u rockk

**Comment by Nawor3565** [comment]
@aliparlakci sorry to necro this issue, but was this feature implemented? I don't see anything that mentions it in the documentation. It would be super useful, as I figured out that you can bypass the 1,000 post limit in certain cases by just requesting a GDPR request on your account. You get a bunch of .csv files, and each one contains a list of **all** your submissions/comments/saved posts/upvoted posts etc. etc. I could make a custom script to download each URL individually, but it seems like reinitializing the program for every single post would take quite awhile. Thanks!

**Comment by Serene-Arc** [comment]
@Nawor3565 Hi, I'm the lead developer at the moment, I rewrote the codebase a little while back. Somewhere recently I wrote a Bash script in one of these issues that will take a list of IDs and use them in a batch run.

```bash
cat links.txt | while read line; do echo "--link" $line; done | xargs python3 -m bdfr download <OPTIONS>
```

This is the Bash snippet. Note that terminals have a max character length for a single command, so you may need to use the following:

```bash
cat links.txt | while read line; do echo "--link" $line; done | xargs -L 50 python3 -m bdfr download <OPTIONS>
```

You can tweak the number 50 to suit whatever limitations that your shell has. If you feel that this isn't a suitable solution for your problem, you can open an enhancement request and I'll get to it soon.

**Comment by Nawor3565** [comment]
Thank you! I would definitely use this, but unfortunately I'm on Windows. I might end up using WSL in the meantime, but a feature request could work too. It would be useful if BDFR could handle the .csv files directly from reddit, which would be simple as they're just formatted like
`post_id,permalink_to_post_or_comment`
I will write up a separate request tomorrow. Also, I just want to thank you for being a great dev, your responsiveness and willingness to address problems and feature requests is really appreciated. :)

**Comment by Serene-Arc** [comment]
Those are very basic bash commands and are compatible with a range of shells. [You can also enable](https://www.laptopmag.com/au/articles/use-bash-shell-windows-10) a Bash shell for Windows.

It's unlikely that we'll implement the ability to read CSV files due to a couple reasons. The variation would make it difficult and for this "base" tool of the BDFR, I'm inclined to follow the Linux rule of "do one thing and do it well". In that vein, it is better to provide a simple list of IDs to the BDFR so that it can download them. It doesn't care where they came from, what order they're in, how they were generated, etc, it just downloads them.

And thanks! I'll get to the request after it's been opened.
