### ISSUE TITLE
When using --no-dupes and --downloaded-posts, the program doesn't record the duplicate posts in the file, causing it to attempt to redownload them the next time the same command is run.

### ISSUE THREAD

**Issue by AwkwardCauliflower** [aliparlakci/bulk-downloader-for-reddit#168]
A very large number of reddit users post the same image multiple times to multiple subreddits.

I really like that your app de-duplicates them, and even seems to hash the files in order to do so. This is great! However, it should also record the duplicates in the `--downloaded-posts` file so that it doesn't try to download them again and again, just to reject them as duplicates.

Running the program for 5 minutes just to see this is pretty annoying:

    There were 151 duplicates
    Nothing is downloaded :(

It's great that it didn't try to re-download the 140 files that already were downloaded, but it shouldn't retry the 151 duplicates, either. It should just exit with a "Nothing to do" style message, or "291 already downloaded or found to be duplicates".

**Comment by Serene-Arc** [comment]
I'll add an option to check the existing filesystem for duplicates. This won't be the default since it's potentially CPU intensive but it'll be a good feature to include. It will involve calculating and caching the MD5 hash for every file already downloaded before the program can actually start downloading, so that'll be a tradeoff that you have to consider. It'll be fine for a hundred files for sure, but when you start getting to thousands it'll add up.

**Comment by Serene-Arc** [comment]
Implemented in v2 beta

**Comment by AwkwardCauliflower** [comment]
I'm sorry. I wasn't clear. Your change doesn't address the problem. I will attempt to make the problem more clear:

A redditor has posted the following files:

CatPhotoA.jpg 18 MB
CatPhotoB.jpg 15 MB

They have made the following posts with these two files:

Post #1: CatPhotoA.jpg in /r/cats. 
Post #2: CatPhotoA.jpg in /r/catswithjobs 
Post #3: CatPhotoB.jpg in /r/cats

Post #1 and #2 are different posts, with their own post ID, obviously, but they are the same photo.

Here is how the program behaves with the options mentioned in my title:

1. Program downloads CatPhotoA.jpg and records the post ID and file hash in the "downloaded-posts" file.
2. Program downloads CatPhotoA.jpg a second time, hashes it, realizes it's a duplicate of post #1, and deletes the file, but doesn't record anything.
3. Program downloads CatPhotoB.jpg and records it in the "downloaded-posts" file.

Now, we run the same command a second time:

1. Program sees the post ID from post #1 in the "downloaded-posts" file and skips it.
2. Program downloads CatPhotoA.jpg *yet again*, hashes it, realizes it's a duplicate of post #1, and deletes the file.
3. Program sees the post ID from post #3 in the "downloaded-posts" file and skips it.

The problem is that for post #2 it downloads the file every time you run the program. Some users post the same file 10 times. When they do, the program downloads it *9 times* every time you run the command! Then deletes it each time. This is because it doesn't record the post ID of post #2 in the "downloaded-posts" file. 

So, my user experience is that the command runs for 5 minutes just to tell me that nothing was downloaded. :( Instead, it should have only taken a few seconds to realize that every post ID has already been recorded in the "downloaded-posts" file.

Solution: When a duplicate file is encountered, record the post ID in the "downloaded-posts" file so that the program knows to skip it when the same command is run again in the future. Rather than repeat the same hash value multiple times in the file, you could create a hierarchy. Maybe using a dict, with the hash as the key, and a list of post IDs as the value. Then save it to a JSON file. Load it and overwrite it (safely) each time the command is run. But I don't need to tell you how to program, you obviously are quite good at it!

Thanks for reading!

**Comment by Serene-Arc** [comment]
No, this is against the ethos I had when coding the project. Databases can be corrupted, destroyed, malformed, or any number of things that then makes the archive itself worse. The BDFR is designed to run from a perfectly clean state to a perfectly clean state, leaving nothing behind but the files themselves.

If this is an issue for you, I recommend using the `--make-hard-links` option when downloading. It will leave a file on the disk linking to the first copy while only taking up the space of one file regardless. Then, on subsequent runs of the BDFR, it will see that a file already exists and skip before downloading.

**Comment by AwkwardCauliflower** [comment]
I don't see how this could be against the ethos when the feature already exists. `--downloaded-posts` already creates a file and stores post ID's and hashes. And it uses this file on subsequent runs of the same command. All I'm asking for is to fix an undesirable behavior when using the existing feature.

> The BDFR is designed to run from a perfectly clean state to a perfectly clean state, leaving nothing behind but the files themselves.

That's simply not true or this feature wouldn't exist. At a minimum, keep the existing file format, and just append *every* post ID and file hash, not just for the first time a file was downloaded.

**Comment by Serene-Arc** [comment]
No it doesn't. Sorry that I'm not clear, the project has a version 2 in beta, which I recoded from scratch since the old version had grown unmaintainable and was exceedingly difficult to modify. The `--downloaded-posts` option no longer exists in v2.

If you wish to code a pull request for v1 and submit that, then it can be merged, but there is no longer going to be active development with the first version of the project.

I would give the de-duplication methods already provided in v2 a try, it sounds like it would solve your problem. The `--make-hard-links` and `--search-existing` would solve this issue.

**Comment by aliparlakci** [comment]
As Serene explained, old version (which was originally written by me) was too hard for me to maintain. v2 is a reimplementation. In the near future, master is going to be replaced by v2 and the old version will remain on a branch.

Although I strongly encouraged you to switch to v2, I plan on fixing bugs in the old version if I have the time. I don't plan on bringing new features to it since I have hard time sparing time to this.

On this issue, `--no-dupes` does exactly this if you also provide --downloaded-posts. Let me know if this solves your issue.

**Comment by AwkwardCauliflower** [comment]
Thank you for clearing everything up.

Just to be clear, the duplicates won't *remain* downloaded (they get deleted), but the program will download them again and again.

Since opening this bug report, I've learned Python and completed two projects with it, so maybe I'll look into fixing this myself in v1.

I can't imagine myself ever using a version of the program that doesn't have a feature to track what's already been downloaded in order to skip it.

**Comment by Serene-Arc** [comment]
The hard links are only created in v2, and they aren't 10 copies of the same file. You misunderstand what hard links are and how they work. All files are references to a section of data on the disk, normally files only have one reference. A hard link is just another reference to the same bit of data. So 10 hard links to the same data takes up the same amount of space as 1 file, because hard links do not duplicate any data.

Hard links are good where the position of the file gives some information e.g. when each directory is a subreddit, but where you also don't want to duplicate any data. 

There are many methods to stop duplicate files from being downloaded and stored in v2. If you want the result without using any of those options, then I'm not sure how I can provide a solution.

**Comment by AwkwardCauliflower** [comment]
Again, sorry I wasn't clear. I know exactly what hard links are. It still results in a file system entry that programs like image viewers will see. They are "duplicates in the file system", which is what I said. I don't care about disk space. I care about seeing 10 file system entries for the same image. I still consider these "copies".

I never download files into subreddit folders. They all go straight into the same folder by author.

If v2 has a mechanism to not waste my time and bandwidth by having to download duplicates over and over just to delete them, and in a way that doesn't leave behind superfluous file system entries, then great! But it doesn't sound like it does or could, because that would require keeping track of the duplicates that were deleted, and that would be an anathema to the project it seems. ¯\\\_(ツ)_/¯

**Comment by Serene-Arc** [comment]
I'm finding it difficult to understand what you're wanting here. You want there to be no duplicates, not even as hard links, yet you don't want to use a naming scheme that would allow that to happen with the first mechanism of not overwriting an existing file name. But you also don't want to download anything more than necessary. 

The reason that this is not done in the project by default is because the BDFR does not assume that the file list is the total sum of the content in the archive, which is rarely the case. There are a lot of reasons for it that I'm not going into here.

A feature currently being tested is a way to skip any given submission IDs. If you want to grep the logging output to find all of the IDs found in a run of the BDFR, then that will likely do as you wish. But it will be on you to keep that list up to date as the BDFR is a stateless downloader.

**Comment by aliparlakci** [comment]
> If v2 has a mechanism to not waste my time and bandwidth by having to download duplicates over and over just to delete them and in a way that doesn't leave behind superfluous file system entries

Yes it can, as Serene stated. I just want to clarify it. You can run the bdfr command in a custom where you will give a text file (say IDs.txt) as `--exclude-id-file` parameter and pipe the output

**Comment by aliparlakci** [comment]
> If v2 has a mechanism to not waste my time and bandwidth by having to download duplicates over and over just to delete them and in a way that doesn't leave behind superfluous file system entries

Yes it can, as Serene stated. I just want to clarify it. You can run the bdfr command with the newly implemented `--exclude-id-file IDs.txt` (this file can be empty at first) parameter and pipe the output to another command to extract the downloaded post IDs and append the output to IDs.txt.

If you are using Linux, it will look something like below. First line saves the output of the program to temporary text file. Grep command selects the relevant lines and awk selects only the IDs on the file. In addition, if you also want to see the console output, replace the `> output.txt` in the first line with `2>&1 | tee output.txt`

```bash
python3 -m bulkredditdownloader download ../downloads --subreddit me_irl -L 20 --exclude-id-file IDs.txt > output.txt
cat output.txt | grep -P 'Downloaded submission' | awk '{ print $(NF-2)} ' >> IDs.txt
```

And if you are using Windows, PowerShell is a such a powerful tool and with a little bit of tinkering, you will find the equivalent command. If you can't, let me know.

**Comment by Serene-Arc** [comment]
Just adding on, you can use my little grep extraction on the "master" log file in the config directory for the program, which will contain all of the shown logging anyway.

Else, if you want to look at the program output at the same time, on Linux you can use the `tee` command, as follows:

```bash
python3 -m bulkredditdownloader download ../downloads --subreddit me_irl -L 20 --exclude-id-file IDs.txt| tee output.txt
cat output.txt | grep -P 'Downloaded submission' | awk '{ print $(NF-2) } ' >> IDs.txt
```

**Comment by aliparlakci** [comment]
This won't be fixed on v1.
