### ISSUE TITLE
1000+ post

### ISSUE THREAD

**Issue by tigerfullx14** [aliparlakci/bulk-downloader-for-reddit#180]
Hey. How to go beyond 1000 subreddit posts limit in bulk-downloader-for-reddit?

**Comment by aliparlakci** [comment]
Unfortunately not :(

**Comment by Iron-E** [comment]
I have two ideas, feel free to comment and/or criticize:

1. Does the Reddit API support paging like the YouTube API? If so it might be possible to continue by querying for the next set of values. I do something like that [here](https://github.com/Iron-E/wisdom-bot/blob/master/src/youtube.rs#L139-L146)
2. The new application [ErGoDownloader](https://github.com/Forceu/ErGoDownloader) allows users to pass an `-unsave` flag in order to remove downloaded posts. This could also allow downloading beyond 1000 saved posts, if the saved posts are removed after downloading successfully.

**Comment by Serene-Arc** [comment]
There is no paging. There is a hard limit on the Reddit API regarding the limit. You'll find that this applies to your own user lists. If you go to a user's profile and they have 1000+ posts, you will only be able to see the latest 1000. There is no way to bypass this with Reddit itself. There are third-party solutions such as Pushshift but those are not used by the BDFR.

**Comment by Iron-E** [comment]
Thanks for the response!

If I understand correctly, does reddit not track more than a thousand a time? So if we unsaved 1 it would not retrieve 2–1001?

**Comment by Serene-Arc** [comment]
I don't know if this feature will come back. All of the BDFR is just scraping data, having actually performing actions and changing data is at odds with the rest of the program, especially if it's just to implement what is honestly a really janky solution.

Another user of the BDFR found a better solution which is to make a GPDR request of your data which will include all of the post IDs that you've upvoted, saved, etc. Then the IDs can be fed into the BDFR to be downloaded.

**Comment by Iron-E** [comment]
I didn't consider a GPDR request. Made one and downloaded it.

Thanks for the suggestion!

**Comment by Serene-Arc** [comment]
Glad it worked :)
