### ISSUE TITLE
Implement typing

### ISSUE THREAD

**Issue by Serene-Arc** [aliparlakci/bulk-downloader-for-reddit#185]
Add typing annotations to the code

**Comment by vladdoster** [comment]
Could you elaborate on this feature a bit more? Specifically the following:

1. Since the Python runtime doesn't enforce type annotation, do you have a library in mind for this?
2. I saw you mentioned doing a refactor soon. Would it make sense to do that first and then add type annotations in an attempt to reduce time on adding type annotations. Is there some immediate benefit by adding type annotations to the non refactored version?

**Comment by Serene-Arc** [comment]
The Python runtime does not, but IDEs can. The `typing` library can do this for some things, otherwise there are built-in types available for every basic object in python.

As for doing this before the refactor, no it makes more sense to get a basic typing annotation system up first, even if some of it is incorrect. There are no tests, and the refactor is designed towards getting the code to a point where it can be tests. Type annotations will make that much, much easier simply by being able to follow object types through methods and classes.
