### ISSUE TITLE
limit (0 for none) does not gets more than 900 posts

### ISSUE THREAD

**Issue by Suryakant-Bharti** [aliparlakci/bulk-downloader-for-reddit#195]
![image](https://user-images.githubusercontent.com/2780145/109478981-e8429b00-7a9f-11eb-92db-dbd9e8f2d563.png)

If I enter 0 here, it shows "GETTING POSTS" and gets a maximum of only around 900 posts.

**Comment by Serene-Arc** [comment]
This is currently not possible. The actual backend that we use is provided by Reddit, the praw package in Python. All backends provided by Reddit provide a *maximum* of 1000 posts to any query, and usually less than that. There is no easy way to change this or to code an alternative ourselves.

The easiest solution would be to switch to Pushshift or another API that provides a wrapper around Reddit but this would require rewriting all of the backend-related stuff, though some functionality would still require praw. There might be other big downsides but it isn't likely to happen any time soon either. A thousand posts is a pretty big limit and if you need or want more than that, it'll have to wait until the rewrite is complete. I'll close this for now though, since it's a known limitation with the API and it won't be circumvented here soon.
