### ISSUE TITLE
V2: Downloading and Archving for Combined HTML Output

### ISSUE THREAD

**Issue by BlipRanger** [aliparlakci/bulk-downloader-for-reddit#209]
I've been looking at a variety of Reddit archivers and I really like this one, but the thing that I feel like it might need is the ability for it to create a clean and easy to navigate archive. So I've started work on a draft for the output type of HTML for the "archive" command because I think that a nice feature would be the ability to generate a set of pages that contain both the posts and their comment sections that are easily navigable in browser. However, because download and archive are two separate actions, it would require running one and then another with aligned configs so that the folder structures matched up, etc. Is there interest in adding a single combined command that performs download and archive and spits out a set of HTML files? Just want to make sure this feature aligns with the vision of the project.

**Comment by Serene-Arc** [comment]
I'm not sure why this is a good fit for the project. If you want en entire set of HTML files for Reddit, then there are other, better tools with which to do that. Scraping and saving a page like that requires parsing Javascript, among others, to get all of the code to make a correct page.

Unless you're asking to make a new HTML page that is just pure HTML from a custom template? In which case I would suggest that it is spun out into a sister project for the BDFR. At the moment, there is a clear division between downloading posts downloading post data, and it *only* downloads either way. This would require a lot of extraneous stuff that wouldn't otherwise be used at all

**Comment by aliparlakci** [comment]
I think that's a great idea. However, I agree with Serene also. It can be a separate project which uses the outputs from BDFR and serves a local webpage to browse the posts.

**Comment by BlipRanger** [comment]
Sure, that makes sense to me! Definitely why I asked first before putting too much into it. I have some work done transforming the the output to html, but will do a little bit of refactoring and will reach out with it when it looks alright.

**Comment by aliparlakci** [comment]
You can be the one to create the project and we can continue the discussion there.

**Comment by BlipRanger** [comment]
> 
> 
> You can be the one to create the project and we can continue the discussion there.

Here is my rough attempt at a script:
https://github.com/BlipRanger/bdfr-html
Let me know what you think.

**Comment by aliparlakci** [comment]
I am closing this issue now as it is no longer related to this very repository. I will write my comments on your repo.
