### ISSUE TITLE
A suggestion to add to this: an option to "skip subreddits"?

### ISSUE THREAD

**Issue by aliparlakci** [aliparlakci/bulk-downloader-for-reddit#219]
A suggestion to add to this: an option to "skip subreddits"?

_Originally posted by @kc2rxo in https://github.com/aliparlakci/bulk-downloader-for-reddit/issues/217#issuecomment-808659921_

**Comment by Serene-Arc** [comment]
@kc2rxo Why do you want this feature? It seems unlikely that you will be downloading a large number of submissions from a subreddit you do not want through any of the methods that the BDFR provides. Indeed, I think the most common use is to download whole specific subreddits at a time. If there are submissions that you absolutely do not want, you can search for the name of the subreddit and delete them after the download has completed if you want, since the default naming scheme puts them all in a single folder.

Can you explain your use case for this feature?

**Comment by kc2rxo** [comment]
I'll explain what I have been using bdfr for to try to answer.

Generally I browse a lot of subreddits with photos and gifs. Previously I would just download all the images manually as I came across them but it became a chore - hence why I started using bdfr. I "save" the posts I wish to download over the course of the day (on my phone at work and at my desk at home) then before going to bed use the CLI tool to download them all. These are across over 30 different subreddits that I have in a custom feed.

My suggestion spawns from the fact I also would like to save other posts from subreddits not in my custom feed but not download them. 

Perhaps there is a better way to do this and I am all ears if so.
