### ISSUE TITLE
No documenation for installing v2 locally

### ISSUE THREAD

**Issue by cgsmith** [aliparlakci/bulk-downloader-for-reddit#240]
I am not sure how to create the build after doing a clone and a pip requirements.

```
~/bulk-downloader-for-reddit$ python3 setup.py 
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
```

**Comment by Serene-Arc** [comment]
This is a non-issue. `python3 setup.py` is not a valid command under any package using setuptools, which is most of them, this is not a unique issue to BDFR.

**Comment by aliparlakci** [comment]
As python is an interpreted language, it does not necessarily have to be built to run. BDfR is designed in a way that it can be "packaged" so that it can be installed and uninstalled. After it is published to pip, you can download+install the package with a single pip command without downloading the repo first.

However, packaging the project is not needed to run the program. You can just go in the root directory of the repo and run on of the example commands in the README.

If you are determined to package it by yourself and install it with pip, the correct command would be `python3 -m pip install .` If you are going to not only use the program but make development on the project, use `python3 -m pip install -e .`

**Comment by Serene-Arc** [comment]
I originally closed this issue due to it not being directly related to the BDFR itself and as such, I considered it out of scope for a github discussion. However it has been pointed out to me that this is not a good way to handle such things. As such, I apologise and I will endeavour to answer this and other questions more fully in the future.

So let's go to the other extreme and give a really long and detailed answer :) The BDFR uses setup tools, which means that running `python3 setup.py` itself won't do anything. However, you can run commands such as `python3 setup.py bdist` to create and installable package (this is how we will package releases). You can also use `python3 setup.py install` to install the package, but this is not recommended. It will install the package, but not with a package manager, which means that uninstalling can be a chore and may require manual deletion of files as nothing is tracking what belongs to the package, *usually*. It will work, but it's better to use pip.

Pip can install from a source directory with `python3 -m pip install .`. In this case, pip uses `setup.py` to install a snapshot of the package from, say, a git repository. This will be the exact package as it exists on disk at that moment. This is great for normal users, and bad for developers. Since changes to the source are not propogated to the install package, you will have to reinstall every time you want to test a change.

Pip provides an option for this though: `python3 -m pip install -e .`. This is like an "editable" install, where pip installs the package in name only. Really, it is a link to the source and thus the changes in the repository can be called immediately from anywhere in the system. Pip will tell you this when it's installing, if you watch closely. When installing normally, it will say something along the lines of `Installed bulkredditdownloader v0.1.0dev115` when installing normally (this version is the number of commits after the last tag, since we use pbr to manage this) but if you use the `-e` option, it will simply say `Install bulkredditdownloader` with no version information, because there is no specific version installed.

Lastly, you can call the BDFR without installing at all, as long as you do so in the root folder of he repository. This is because Python adds the current directory to the `path` variable when searching for modules. This is a perfectly fine and workable way to run the BDFR, but installing is generally less of a hassle.

Hope this clears some things up.

**Comment by 4DeepThought2** [comment]
Installing locally, isn't making any sense to me either :) 
I've got all the requirements installed, as well as bdist.  Anything I run though, just fails with various errors. 
Im sure it has to do with moving from v1 -> v2, and not having source files or a starting script to run through.  Excited to watch the progress though, hope it becomes easier to use. Thanks for your work.

**Comment by Serene-Arc** [comment]
What do you mean? Generally, installing a Python package like this, from the root folder, can be achieved with the command `python3 -m pip install .`. It will install any requirements and anything that's needed.

If you are just downloading the source for some reason, and not using git to do so, then our packaging manager will freak out. PBR needs some way to version the package, which we do naturally through git tags and commits. You can work around this though with the following command:

```bash
export PBR_VERSION=0.1.0
```
