### ISSUE TITLE
[BUG] File Scheme {DATE} returns a UNIX Timestamp instead of formatted date

### ISSUE THREAD

**Issue by StuffonGithub** [aliparlakci/bulk-downloader-for-reddit#295]
- [x] I am reporting a bug.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](README.md#configuration)
  
## Description
Using the command below, the {DATE} parameter returns a different format than the previous version.
Actual example: `1618940992.0` in the file name instead of `2021-04-20_17-49`

## Command
```
python3 -m bdfr download '~\bdfr\redditor' --user USERNAME --submitted --sort new --no-dupes --folder-scheme '{REDDITOR}' --file-scheme '{DATE}_{REDDITOR}_{TITLE}_{POSTID}'
```

## Environment (please complete the following information):
 - OS: Windows 10 20H2
 - Python version: 3.9.4

## Logs
I, weirdly, don't have a bdfr folder appearing in my %AppData% directory as stated in the readme. Can't find it anywhere either. But it might not be needed for this specific issue?

**Comment by StuffonGithub** [comment]
@Serene-Arc Thanks so much for the quick fix! I couldn't wait so I manually updated the two files you changed in your commit and can confirm it works on my end too.

Follow up though, if you don't mind. Is there a way that I can somewhat customise the format myself? I'm only asking this because I already have hundreds of thousands of files archived from both users and subreddits using BDFRv1 with the `{DATE}_{REDDITOR}_{TITLE}_{POSTID}` naming scheme and the file name is basically like this: `2021-04-20_17-49_[...]`. But after updating based on your commit, the date format now shows as `2021-04-20T174934_[...]`. 

Although, I would have personally preferred your format, I also think having to redownload everything from the start would be a bit inefficient. Mainly because a lot would have been deleted/removed by now and having a mixed format would also cause a lot of duplicates as well as a minor dent in sorting.

I went ahead and tried to "solve" it on my own first but was only able to find the format mentioned in tests/test_file_name_formatter.py (lines 41, 325, 326, 327). I tried changing those just to check if it would work but obviously it didn't. Haha. To be fair though, I don't know even the basics of coding/programming so I had no idea what I was doing in the first place. 😅

Thanks again for the quick fix and sorry for the wall of text. ❤

**Comment by Serene-Arc** [comment]
I am somewhat reluctant to change the time format in the program itself. The format currently used is ISO format, specifically ISO 8601. The big advantage of this is that it is a standard that many people will recognise, and there isn't any of the confusion with, say, Americans putting the month before the day when representing a date.

That being said, it would be fairly simple to allow a configuration value where you could specify the timestamp format. This is one option.

The second option is that I can try to write a simple python script that will rename the files for you and convert them to this timestamp format (ISO 8601). This is likely to be fairly simple with regex. This is option 2. 

As a user, which option would you prefer? I feel there is an inherent superiority to the ISO format but if you wish to abandon it then I will accommodate that.

**Comment by Serene-Arc** [comment]
After conferring with the project owner, it was decided that keeping the ISO format static would be the best way. However, I did whip up a quick tool that should convert any timestamps of the old format to the new format. That tool is [here](https://github.com/Serene-Arc/timestamp-converter) and there's an example command given. I highly recommend using the `--no-act` flag to see what will happen without changing anything.

**Comment by StuffonGithub** [comment]
@Serene-Arc Hi, thanks for the quick reply yet again! And yeah, I do agree that the current format is better that's why I only asked if there was a way that I can personally customise my own BDFR version so that it will use the old naming convention.

Tbh, I haven't thought of just renaming the old files and that's just brilliant! Only downside is I have to reupload them all again to several online backups but that's a small (and considerably better) price to pay so I can still keep potentially deleted content in the same directory.

And **WOW**, thanks for taking the time to make that tool. I will check it out when I'm home. I know you said it's just simple regex stuff but I've played around with simple python scripts before and I honestly can't get my head around them so thank so much for that.

And can I also say thank you so much for helping out ali with the new BDFR, he's done a fantastic job before but it's understandable that he didn't have enough time for the project and couldn't push updates as much as he wanted. But since you, it's been infinitely better and personally, I love the fact that I can run different scheme systems just through the command line now without having to manually change the config. Makes file management much easier! ❤❤❤

**Comment by Serene-Arc** [comment]
There are a few backup tools that look at the file content rather than the filename but I'm not sure off the top of my head.

If you really really wanted to just customise it yourself then I can tell you what lines to change and so on, but I'd give the tool a chance first, just so there's not any issues keeping up to date in the future.

Also, I recommend running the tool on a small subsection of your old files, or maybe make a full backup, first. Changing names like this always has some risks. I tested the tool and made sure it works on my end, but I'd by lying if I could say it'll work in 100% of cases. It was the product of one evening's work, so make sure that it provides what you're looking for. If it crashes or misbehaves, you can open an issue on that repository and I'll fix it. As can be seen from the BDFR, naming stuff can be pretty complicated and hard to get right.

And thanks! I'm glad that you're enjoying v2 :) I'm definitely trying to keep it as a script as much as possible for things like, configurable from the command line is something I feel is pretty important in archivers and downloaders like this.

**Comment by StuffonGithub** [comment]
Yeah, mine gives me options but the quickest is always checking the file name and file size. I did a hash check once for a different set of files and it took forever. Haha.

And thanks for the offer but as you pointed out, following the ISO 8601 is better for "future-proofing" my BDFR too. That way I don't have to manually change stuff every time. So I will definitely give your tool a try first. 😄

>...configurable from the command line is something I feel is pretty important in archivers and downloaders like this.

I agree, especially for a site like Reddit. I have different sorting and directory tree depending on the content and the source so this definitely makes it versatile and much easier to use.

Thank you so much again for all the work and all the help! 🥰

**Comment by DennisPing** [comment]
@Serene-Arc Hi, I've been following this datetime issue. I'm currently using the dev branch and everything works as you intended. 

I have personally been using the file format `{%Y-%m-%d}-{TITLE}-{POSTID}` since BDFR v1. I exclude the hours, minutes, seconds values. I can manually edit the _convert_timestamp() function to suit my own needs, but **would you consider extracting the `datetime` variables so that a user can edit the format of the {DATE} key?**

Another workaround is to use the `master` branch which uses UNIX timestamps --> download everything --> use your `timestamp-converter` script --> specify the time format as '%Y-%m-%d. But this is an awk workaround which will break when your merge your dev branch later. 😓

**Comment by Serene-Arc** [comment]
@DennisPing  As discussed above, I think that there are benefits to using ISO 8601 moving forwards. You can use my timestamp conversion tool to convert it to ISO if you prefer, and use the dev branch until the next release. Why can't you use the ISO format provided?

**Comment by DennisPing** [comment]
I want `YYYY-mm-dd` instead of `YYYY-mm-ddTHH-MM-SS` because all my other archive files (videos, images, manga, etc) are saved in this format via other scraping tools. I don't necessarily require the extra datetime chars. 

People who use databases properly would probably use the standardized ISO 8601 format. I agree on keeping this the default {DATE} key. But I would like the option to use a shorter `YYYY-mm-dd` format. Nevertheless, I changed 1 line of code to suit my needs, so it's not a deal breaker at all.

**Comment by Serene-Arc** [comment]
@DennisPing  I suppose that there isn't much of a reason to prohibit providing a string. If you could open an enhancement request, I'll get onto it.

**Comment by Serene-Arc** [comment]
@StuffonGithub Just a ping to let you know that customisable date formats were implemented in the end, in case your use case could still use them.

**Comment by StuffonGithub** [comment]
@Serene-Arc Thanks for remembering me! 🥰 Unfortunately, I've already converted everything and has updated my whole archive to the default format. Haha what can I say, I'm more of a conformist than a revolutionary, just a sheep really. 🐑  

Plus, I don't think I have it in me to do it all over again. I hate archiving Reddit content. I swear if BDFR didn't exist when my last archiver shat the bed, I probably would have abandoned this project right there and then. Sorry, I'm **ram**bling. Haha get it? 🐏🐏🐏

Hahahahahahahahahaha. I'm really sorry. ❤

**Comment by Serene-Arc** [comment]
@StuffonGithub lol it's fine, ISO is really the better long term option. I really wouldn't recommend using the customisation at all, it's really just for an edge case where you absolutely need it. IMO it's better to convert to ISO and stick with it if you can, but in the interest of the most amount of customisation possible, it was implemented anyway
