### ISSUE TITLE
[FEATURE] Add option to make symbolic links

### ISSUE THREAD

**Issue by parasiteoflife** [aliparlakci/bulk-downloader-for-reddit#380]
- [x] I am requesting a feature.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](../../README.md#configuration)
  
## Description
Currently there is an option to creat hardlink for duplicates, could you also add an option to create symbolic links (if possible relatives) too?

**Comment by Serene-Arc** [comment]
@parasiteoflife Why do you want this option? Symbolic links are worse for files in most senses, what is your use case for this feature?

**Comment by parasiteoflife** [comment]
What I like more about symbolic links than hard links is that is easier to identify them than to identify a hard link -at least in Windows-, at first glance you can see that's not a file but a symlink. Besides that, all my workflow is acomodated around symlinks, it's what I've always used, every duplicate I had has been replaced by a symbolic link by different programs (DupeGuru, Duplicate File Detective, etc.).

**Comment by Serene-Arc** [comment]
Well, all hardlinks are equivalent: each file is technically a hardlink. You can identify them easily enough in Linux, I don't know about Windows. I would strongly advise against using symbolic links to link to files in this manner, very very strongly. This isn't a very good use for them. But, I guess if you want them, they should be easy enough to implement.

**Comment by aliparlakci** [comment]
I couldn't see the reason behind this request. What problem do you think being able to tell if file is a symbolic link or not solve for you?

My first thought was the fear of deleting the original but I found out that after creation of a hard link, there is no such thing as original. File is actually deleted when there are no links to it anymore.

In that case, symlinks has a lot of reasons to get abandoned.

**Comment by Serene-Arc** [comment]
Yeah that's my thought as well. Moving or deleting the file will result in a symlink that doesn't lead anywhere. I know in Linux, symlinks are used between files that aren't going to move, like between program executables in different directories. Using them in an archive seems counterproductive, especially since it requires that the files in the archive remain static and aren't moved or anything. One of the strengths of the BDFR is it's lack of a central database so that the files can be manipulated outside of the BDFR itself.

**Comment by aliparlakci** [comment]
Closing this issue since there has been no justification of the feature.
