### ISSUE TITLE
[FEATURE] Original Post Timestamp

### ISSUE THREAD

**Issue by sgtsilver** [aliparlakci/bulk-downloader-for-reddit#387]
I don't see a feature yet that keeps the original posts Timestamp, is this in the works or planned?

**Comment by Serene-Arc** [comment]
What do you mean? You can include the time stamp of the post in the file name.

**Comment by sgtsilver** [comment]
Hi there, I meant that the actual file timestamp is set to the time when the post was made

**Comment by Serene-Arc** [comment]
Ah, I see. Very well, I think this is something that's a good feature to add.

**Comment by ymgenesis** [comment]
So this means now that created and modified dates are the dates the post was made? Is there a way to change it back to keep the metadata creation or modified as the date it was downloaded by bdfr?

I have a 'recent' folder that finds all recently downloaded content with find and -mtime, and makes hard links to those files into the recent folder. it relies on the files' modified time to make the hard links, which used to be the time the files were downloaded. Just realized now that my recent folder went from working properly, to only having like 7 hard links because those 7 were posted so recently that it met my find -mtime n criteria. Instead, there should've been a couple hundred which were downloaded minutes before. Hopefully I'm getting my point across clearly.

**Comment by Serene-Arc** [comment]
I suppose yeah, you'd have to remove that part of the code. It's a bit of an odd use case to want "new" files but not actually new posts.
