### ISSUE TITLE
[FEATURE] HTML export format

### ISSUE THREAD

**Issue by Ailothaen** [aliparlakci/bulk-downloader-for-reddit#393]
- [ x ] I am requesting a feature.
- [ x ] I am running the latest version of BDfR
- [ x ] I have read the [Opening an issue](../../README.md#configuration)
  
Hello!

I heard about the project some time ago (from r/datahoarder I think), and I have to say I am enthusiasted by it, as I find Reddit to be a community with a lot of interesting content.

Some time ago, I actually wrote my own program to archive Reddit threads. Still, it is way more limited than BDFR, as it can only save the text of an individual thread. However, I took time to implement an HTML render, so you are able to browse through an archive of a thread in a comfortable way.

Here is an example (the .html file is standalone, it requires no other file to be readable) : https://ailothaen.fr/i/example_html_bdfr.html

In particular, there is some "navigation" features. If you click on the "O" icon of a post, you are then able to navigate through sibling same-level comments by pressing up and down arrow keys (or clicking on up/down arrows), or go to the parent with pressing the P key or clicking the square icon.

Therefore, my suggestion would be: what do you think about adding this output format in BDFR (with `-f html`, I guess) ? Do you have some suggestions to make the render better? (Of course I could take care of adding the output format myself)

P.S.: the "Opening an issue" link above looks broken

**Comment by aliparlakci** [comment]
Since rendering an HTML is not in the scope of this project, bdfr won't have a `-f html` option. BDFR only focuses on getting the content, nothing more.

However, I am planning to implement another tool (outside the bdfr repository) which uses the output of bdfr to create a web interface similar to your example. But I'm strongly against implementing a HTML generator as making a good UI would be nearly impossible. I will probably use a web framework/library. I reckon the project will be somewhat functioning in a month and I will share it then. 

I suggest you to not waste your time on creating an HTML generator either. It is not very pleasant to deal with. There are people out there that invested great amounts of time and made awesome tools. No need to invent the wheel again.

**Comment by Ailothaen** [comment]
Thank you for the feedback!

So yeah I get it, BDFR is only about the content, not presentation. I will be staying tuned for your web interface project.

However, I disagree about the last part: my HTML "generator" is already made anyway, and was not that hard to implement. I am all for not reinventing the wheel (which is also why I made that issue here instead of keeping it for myself), but I doubt other tools would have been useful in my case, as Reddit has a particular format that is not as straightforward as a standard "question/answer" design. (Plus, I tend to be careful about things like Angular or React, since they are way too oversized for most projects + I wanted to keep the output files as small as possible)

**Comment by aliparlakci** [comment]
I think it depends on what you aim for. In my case, HTML generator is a no-go as I want the pages to be interactable thus needing JS. If you only want to view your post details in a more pleasant way, then yes, running a web framework would be an absolute overkill.

But I disagree about the sizes. Those frameworks are notorious for big bundles but it is only relevant if you are on the web. If they are meant to live on your hard drive, they are actually smaller. Your example HTML is 22KB. 1000 posts of HTML is 22MB whereas the entire React build is only 1MB. This issue page is even 1.8MB. You can go even smaller with Preact.
