### ISSUE TITLE
[FEATURE] Mention of BDfR-HTML as related project in readme

### ISSUE THREAD

**Issue by BlipRanger** [aliparlakci/bulk-downloader-for-reddit#423]
- [ x] I am requesting a feature.
- [x ] I am running the latest version of BDfR
- [x ] I have read the [Opening an issue](../../README.md#configuration)
  
## Description
This is actually more of a docs request I suppose. I wanted to ask if it might be possible that the [bdfr-html](https://github.com/BlipRanger/bdfr-html) project be mentioned as a related/spinoff project somewhere in the docs/readme. The project has matured a bit and now has a docker-compose setup that actively uses BDfR to preform archival on a timed basis. I'd simply ask that you take a look at the project and consider having a link somewhere if you think it's worthwhile. If not, I totally understand and won't request this again. Thanks!

**Comment by aliparlakci** [comment]
First of all, bdfr-html is really a great project and I think you did an awesome job. Thanks a lot :)

However, as soon as I mention it on README, I will get responsible for bdfr-html. But I have no right to interfere and decide about bdfr-html and it should stay that way as well. Because it is your project, 100% your work and you should be the one to make the final decision. Thus, I won't be able to put it in the project's page unfortunately. I hope that you understand me.

Finally, if there is anything in bdfr that is limiting you in bdfr-html, don't be hesitant to open an issue here and we will try our best to make it work.

Keep up the good work!

**Comment by BlipRanger** [comment]
No problem! Thanks for you consideration and thank you for the compliments, it means a lot. I'll definitely continue to provide feedback!
