### ISSUE TITLE
[FEATURE] Skip hash calculation if there is no submission to download

### ISSUE THREAD

**Issue by OMEGARAZER** [aliparlakci/bulk-downloader-for-reddit#428]
- [X] I am requesting a feature.
- [X] I am running the latest version of BDfR
- [X] I have read the [Opening an issue](../../README.md#configuration)
  
## Description
When running through list of users to download/archive while using --search-existing the script will generate hashes before checking if the user is available (not deleted/suspended/banned) which can take 10+ minutes before moving on and needing to generate the hashes all over. As suspensions can be temporary I think it would be best to check for this case before processing hashes to avoid a useless hash as there is currently no way to save the hashes for future use (that I've seen anyway)

![hashing](https://user-images.githubusercontent.com/869111/119543793-0fd39780-bd5f-11eb-95a7-9845f4763a5b.PNG)

If possible, check user before hashing files to save time, or allow a way to store hashes and ID to not require rehashing every run.

Thank you.

**Comment by aliparlakci** [comment]
Can you share your opinion on this @Serene-Arc?

**Comment by Serene-Arc** [comment]
I don't know if this is technically feasible at all, and I don't think it's a good idea regardless. Due to how praw works, we don't know how many submissions---if any---are going to be returned by a request until we begin to iterate over the submissions. 

Also, the BDFR is equipped to download the same data from multiple users in the same run. If, say, you want to download the submissions from all the users, you can specify `--user` multiple times in the same command. That means the hash calculations will only run once for that set of users.

Lastly, it is pretty easy and much faster, to use a third party tool to achieve the same results. I personally rarely use the `--search-existing` option anymore precisely for that reason. Instead, I download it normally and then, after a few runs, use rdfind to make hard links between duplicate files. Programs like rdfind use more advanced heuristics to determine duplicates, like comparing the first few bytes and then the last few bytes, instead of doing the intensive computations required to calculate a full hash. Unless you are running right up against your storage limits, in which case you probably shouldn't be archiving stuff, the trade-off is minimal with this approach.

**Comment by OMEGARAZER** [comment]
> Also, the BDFR is equipped to download the same data from multiple users in the same run. If, say, you want to download the submissions from all the users, you can specify `--user` multiple times in the same command.

Probably should have, but didn't, realize this. I guess now my request should be to allow a "username file". using --user multiple times will solve the issue for me though, thanks.

**Comment by Serene-Arc** [comment]
Uh...no, sorry, there isn't. Just me being an idiot. Apparently I thought that in my head and then didn't actually implement it. If you'll open an enhancement request, I'll get to that today.
