### ISSUE TITLE
[FEATURE] Storing of hashes and using them for exclusion

### ISSUE THREAD

**Issue by BeeMuffins** [aliparlakci/bulk-downloader-for-reddit#430]
- [X] I am requesting a feature.
- [X] I am running the latest version of BDfR
- [X] I have read the [Opening an issue](../../README.md#configuration)
  
## Description
Similar to ```--exclude-id``` and ```--exclude-id-file```, is it possible to add a feature where the calculated hashes when using ```--search-existing``` are stored to a hash file which could then be read in when executing commands to prevent the same hashes from having to be generated every time.  I've notices that within the log file there is already ```Hash added to master list:```, but I'm not sure where that mater list is saved to or how it can be used for future runs to prevent hash calculation on a large number of files.

Right now I'm grepping the log files to generate my IDs for use with ```--exclude-id-file``` and feel that being able to do something like that with the hashes would be a big time saver for large directories.

**Comment by Serene-Arc** [comment]
This has been discussed before and it won't be added. The BDFR does not keep the state of the archive anywhere from run to run. The `--search-existing` option is more of a "there if you want it" feature, but it is only a bandaid. It is a bad implementation because most of the backend was already there. We already calculate the hash of every download, this just calculates the hash of every file already in the destination beforehand but it does not work well at scale.

Hashing is computationally intensive and is not the best way to determine duplicates in actuality. It is definitive, yes, but not the most efficient. Tools like rdfind are available in all major Linux repositories and will do that job far better and faster than the BDFR itself. Tools such as this compare the first few bytes and last few bytes, for example, rather than calculating all hashes outright, making them much faster. You can run rdfind after each run or (what I recommend) after several runs to clear up the duplicates on disk.

**Comment by BeeMuffins** [comment]
Thanks for your response, I wasn't aware of the previous discussions and didn't see it come up in my search of issues.  Appreciate the tip on rdfind, I just started using it and it is just want I needed.  While testing some of my directories, it's not perfect, but it picks up a lot of the duplicates and is much much faster than the full hash calculation.
