### ISSUE TITLE
Saved Posts Limit

### ISSUE THREAD

**Issue by ardittristan** [aliparlakci/bulk-downloader-for-reddit#47]
I have been using the program for a month or two now and I have been noticing that the amount of saved posts it can load are between 920 and 1000 because I have been adding new saved posts during those months but the counter has never passed 1000.

**Comment by aliparlakci** [comment]
It has nothing to do with the script. Reddit's itself has those limits. You can't load more than 1000 posts at a time. For multireddits, it's 1000 posts for each subreddit. Saved posts overflow after 1000 posts. It's the reason why this program logs posts to a file for downloading later.

Set your preferences to see 100 posts per page and you will see you cannot go past 10th page because of that.

Lastly, please use the latest version of program as they are fatal bugs in older versions. For example, on older versions, it cannot download Gfycat posts anymore as they are changed their gif pages.

**Comment by laggingreflex** [comment]
Doesn't reddit API support pagination? Using the "after" id:

https://www.reddit.com/dev/api/#GET_user_%7Busername%7D_saved

Great project BTW. Just stumbled across it. I too would really love to download all of my saved post.

**Comment by Serene-Arc** [comment]
Just adding on, we use praw which is a python package that abstracts away the direct API calls to Reddit. But yes, the 1000 post limit is a hard one that is not easy to bypass, and there's no way to do it "officially". Some tools like pushift manage to get past it, somehow, but I don't know what they do to do so, and it would likely mean changing the entire backend of the BDFR at this point.

**Comment by laggingreflex** [comment]
I see. It seems reddit doesn't even allow viewing more than 1000 posts on its own website either (by clicking next page it only goes till 9th page). Sucks!

I think pushshift maintains its own database by scraping reddit. So while it may get past the 1000 limit for general data, it still probably won't be able to get your (user's) personal saved/upvoted posts. 

On a separate note, since I personally was particularly interested in getting all my saved/upvoted posts. It seems the only way to get all your full data is to do a data-request: https://www.reddit.com/settings/data-request. I've just done it, it says it'll take a while (<30 days) not sure what format it's gonna be in. I hope there will be a way to download using that.

**Comment by Serene-Arc** [comment]
@laggingreflex in some way, it will certainly involve the resources IDs which you can then pass to the BDFR after the fact.
