### ISSUE TITLE
bdfr 2.2 uses praw 7.2.0, while current version is 7.3.0.

### ISSUE THREAD

**Issue by ymgenesis** [aliparlakci/bulk-downloader-for-reddit#486]
- [ ] I am reporting a bug.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)
  
## Description
Log warns that praw is outdated each time a new download is started:
```
Version 7.2.0 of praw is outdated. Version 7.3.0 was released Thursday June 17, 2021.
```
Not necessarily a bug, but I'm wondering if praw could be updated to 7.3.0 safely.

Running `python3 -m pip install bdfr --upgrade` says praw is satisfied at 7.2.0 and doesn't update to 7.3.0:
```
Requirement already satisfied, skipping upgrade: praw>=7.2.0 in /path/to/python3.9/site-packages (from bdfr) (7.2.0)
```
Has bdfr been tested with praw 7.3.0?

## Environment (please complete the following information):
 - OS: Linux Ubuntu 20.04
 - Python version: 3.9.5

**Comment by Serene-Arc** [comment]
It has been tested in 7.3.0 because that's what I've been using for a while, so it does work. As long as 7.2.0 works though, there isn't really anything that we can do. We don't use any of the new features in 7.3.0 so it's best to keep backwards compatibility unless it's actively broken.

I think that this issue is mainly due to a pip thing. Python3's pip has recently gone through some major changes regarding dependency resolution and update mechanics. First, try to update praw directly if it's bothering you, with the command `python3 -m pip install -U praw`. That should do it but also consider updating pip with `python3 -m pip install -U praw`. 

As far a pip is concerned, with the command you typed, the BDFR is fully updated and all dependencies are satisfied, so there's nothing for it to do. If you were to uninstall the BDFR and praw and the other dependencies, then it would probably update when you reinstalled it.

**Comment by aliparlakci** [comment]
I think `--upgrade` does not work recursively. `pip install praw --upgrade` should do the trick.
