### ISSUE TITLE
[FEATURE] cache file hashes

### ISSUE THREAD

**Issue by laundmo** [aliparlakci/bulk-downloader-for-reddit#497]
- [x] I am requesting a feature.
- [x] I am running the latest version of BDfR
- [ ] I have read the [Opening an issue](../../README.md#configuration) - ERROR 404 not found.
  
## Description
Im in the process of downloading a lot of images on a low bandwidth and on a bad device. there are common disconnects, device crashes or other things that interrupt BDFR. Every time it spends longer and longer calculating file hashes. cashing these should reduce load by quite a bit and lead to a faster startup time. the cache should likely be based on filename + change date, with a option to re-scan hashes fully when something knowingly changes files.

**Comment by Serene-Arc** [comment]
This is something that's been suggested before and it won't be implemented. The `--search-existing` option is not recommended for most applications. The BDFR doesn't keep any records between runs, such as file hashes, so that there are no misconceptions about the library, which may change without the BDFR's knowledge. This means that libraries can be split, combined, or altered without hurting later runs.

The proper way to do what you want is to extract the IDs that have been processed on the last run of the BDFR, using the scripts in the `scripts/` folder, and then adding these IDs to a master exclude file. This ensures that every submission will only be downloaded once.

If you want absolutely no duplicates, use a tool like `rdfind`. It is much, much smarter than the implementation used in the `--search-existing` option. Calculating file hashes is a computationally expensive operation so dedicated tools like `rdfind` use numerous shortcuts to speed up the process. So after the run, just run that and it'll determine all duplicate files for you.
