### ISSUE TITLE
[BUG] Archive mode should support --file-scheme

### ISSUE THREAD

**Issue by notevenaperson** [aliparlakci/bulk-downloader-for-reddit#531]
- [X] I am running the latest version of BDfR
- [X] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)
  
## Description
When using the `archive` mode, I want the JSON files it saves to include the date. `clone` mode does conform to file-scheme when it saves JSON files. Why can't `archive` do it too?
## Command
```sh
python3 -m bdfr archive . --file-scheme '{DATE}_{TITLE}_{POSTID}' --subreddit all
```

## Environment:
 - Arch Linux
 - Python 3.9.7

## Logs
```
Usage: python -m bdfr archive [OPTIONS] DIRECTORY
Try 'python -m bdfr archive --help' for help.

Error: No such option: --file-scheme
```

**Comment by bigbluedeer** [comment]
It does support it (because how else would it work on cloner), its just not provided as a cli argument (this might have a reason, so be cautious). To use it you need to set it manually in the config instance. 

If you know your way around click you could modify "bdfr.\_\_main\_\_" to include it as a cli argument. Or you can just insert `config.folder_scheme = "..."` after line 96 in "bdfr.\_\_main\_\_" (though you need to modify this every time you want to change the folder scheme). If you want to set it manually in a script, you can use something like this:

```python
from bdfr.configuration import Configuration
from bdfr.archiver import Archiver
from bdfr.__main__ import setup_logging
folder_scheme = "..."  # custom folder scheme

config = Configuration()
# set other config here, read "bdfr/configuration.py" and the documentation for more info
config.folder_scheme = folder_scheme
setup_logging(config.verbose)  # from bdfr.__main__
Archiver(config).download()
```

**Comment by Serene-Arc** [comment]
It's been a while, but I don't remember any compelling reason for the feature to not work. Might have just been an oversight, I've been busy over the past couple months but I'll write up a PR and tests for it soon, see if I did have a reason when I wrote it.
