### ISSUE TITLE
[BUG] BDFR fails to write if the file contains any invalid character

### ISSUE THREAD

**Issue by rahaaatul** [aliparlakci/bulk-downloader-for-reddit#593]
- [x] I am reporting a bug.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)
  
## Description
On Android, if I download with the file scheme `{TITLE}`, and if it contains any invalid characters like "?", BDFR fails to download the file.

```
[Errno 1] Operation not permitted
```

## Environment:
 - OS: Android 11
 - Python version: 3.10.2
 - App: Termux

## Suggestion

**Replace the invalid character** with some valid character like "_".

**Comment by Serene-Arc** [comment]
This is an issue due to being on Android specifically. I'm not sure if adding explicit support for Android is something that we'll do, because there are a lot of issues with doing so. The primary one is that Python on Android is not standard, and is missing several features that all Python installations should have, and that are used by the BDFR. 

Fixing this issue itself would be rather easy, but I don't know how much value there is in half-supporting an OS
