### ISSUE TITLE
Documentation and config.json

### ISSUE THREAD

**Issue by stared** [aliparlakci/bulk-downloader-for-reddit#60]
I like this project. It works like a charm. Though, it took me some time to run it.

* Does not automatically create `config.json` if it does not exists. Instead, it produces an obscure error (instead of creating this file).
* The main readme page does not contain direct commands - had to manually look in docs.

**Comment by aliparlakci** [comment]
It is a bug that I have been aware of for couple of days. Because I am
currently studying for university attendance test and I also am the only
person maintaining the project, I could not completely test the latest
release.

I thank you so much for your feedback. I am so happy to see you appreciate
my project.

I will try my best to patch the bug as fast as I can.

Also, what information exactly you hope to see on the README page?

**Comment by stared** [comment]
No rush.

For README - at least linking to command line interface. If you are fine with that, I can modify and do a Pull Request. (Just let me know.)

Also, in a similar spirit (barrier of entry) - would it be possible to make it pip-installable without downloading? Vide https://github.com/stared/livelossplot and `pip install git+git://github.com/stared/livelossplot.git`? I mean, it makes it even easier to install and update when needed. Though, I am not sure if it is easy for a command-line tool.

**Comment by aliparlakci** [comment]
I would be grateful if you can make a pull request.

Implementing such feature demands so much time, which I don't have currently, from me. I have some other cool ideas that I am thinking about implementing later for it though. I will keep in mind your suggestion.

**Comment by aliparlakci** [comment]
I fixed the bug.

**Comment by aliparlakci** [comment]
You did a marvelous job redesigning the README page. Thank you very much!

**Comment by stared** [comment]
@aliparlakci Thank you for creating this script in the first place! :)
