### ISSUE TITLE
[FEATURE] Add option to limit file name length

### ISSUE THREAD

**Issue by markswam** [aliparlakci/bulk-downloader-for-reddit#647]
- [x] I am requesting a feature.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](../../README.md#configuration)
  
## Description
Reddit allows users to create post titles that are up to 300 characters in length, and quite a number of users take full advantage of that and create overly-verbose titles. This poses a problem as the majority of operating systems, by default, have a path length limit of 255 characters (as of the Anniversary update, Windows 10 and beyond allow you to expand this, but not everyone runs Windows 10/11, and a significant number of applications have not been updated to take advantage of this. Bulk Rename Utility, for example).

Specific example: I run this downloader on my Windows machine and end up with paths that are either close to or over 255 characters in length. I then run a periodic backup to an unRAID server using rsync. Files that have a path >255 characters will not transfer at all and instead throw errors. Meanwhile, files that are under-but-close-to 255 characters will transfer, but then can get stuck (cannot open, copy, move, or rename, only delete) due to /mnt/user/\<share\>/BDFR/Downloads/\<user\>/\<subreddit\>/\<file\> being longer than D:/BDFR/Downloads/\<user\>/\<subreddit\>/\<file\>.

I am therefore requesting the ability to specify a user-configurable maximum length for filenames. IMO it would make the most sense to truncate the {TITLE} portion of the file scheme as that's the only portion that can be obnoxiously long.

**Comment by Serene-Arc** [comment]
We already implement this feature. The BDFR already truncates the filename as much as possible given the download location on the system specified by the user. If you wish to move files, then you will need to do your own truncation, or use a filesystem that can handle longer paths. Your unRAID server should have the option for several thousand characters in the full path, which is the norm for most Linux systems.

If you are encountering errors where the BDFR is attempting to write filenames that are too long during the normal course of the program, please open a bug ticket with the appropriate details so that I can investigate.
