### ISSUE TITLE
Enhancement - dedupe hashing possible improvements

### ISSUE THREAD

**Issue by SethBodine** [aliparlakci/bulk-downloader-for-reddit#717]
- [x] I am requesting a feature.
- [x] I am running the latest version of BDfR
- [ ] I have read the [Opening an issue](../../README.md#configuration) <-- 404d

## Description

When scraping several subreddits, the number of files to compute the MD5 hashes for will increase with the current design, This can cause significant delays in downloading new/missing content when using the --no-dupes and --search-existing are used.

When specifying the "root directory" for a user/subreddit, the contents are downloaded and stored in a new sub folder, however the MD5 hashes are for all files and folders in root (which could include other files unrelated to the user/subreddit in question) are also hashed...

While I like the hashing and dedupe features the following options might complicate, but reduce the overhead for these activities...

_Note: I'm using --folder-scheme {SUBREDDIT} to compile all posts from all users into a single folder, and {REDDITOR} for all posts from a single redditor across several subreddits into a single folder - hence the request_ 

- Add a flag that creates a local hash file for the root directory (stored in the root directory that can be used as a base of hashes going forward). Then only new files are hashed as they're downloaded (flag to update the hash list). This could be broken out into individual folders to allow for more granular pre-hashes to be created...May just add complexity and noise though...

- Add a flag to remove the create folder feature (so the root directory ends up being purely for the user/subreddit - thus the hash growth is a lot slower, and the overhead is low).

- Add a flag to hash only the folder created as part of the --folder-scheme argument (reduced overhead, and faster approach).

**Comment by Serene-Arc** [comment]
This will not be done. Honestly the only reason that `--search-existing` still exists in the BDFR is that removing it would technically be a backwards-incompatible change and thus necessitate a major version increment. Since it's not worth making the BDFR 3 over just this change, here it dwells, the 'feature' I wish that I never made.

As has been discussed [many](https://github.com/aliparlakci/bulk-downloader-for-reddit/issues/651), [many](https://github.com/aliparlakci/bulk-downloader-for-reddit/issues/411), [many](https://github.com/aliparlakci/bulk-downloader-for-reddit/issues/505), [many](https://github.com/aliparlakci/bulk-downloader-for-reddit/discussions/585) times before, the use of this feature is heavily discouraged. File deduplication is an intensive process and there are many tricks to speed it up, tricks that the BDFR does not use. Usually MD5 hashes are the last step. I recommend using `--no-dupes` if you really care and then using a third-part tool like `rdfind` to save disk space by either deleting items or making hard links.

My aim with the BDFR is to embody the Unix philosophy of *do one thing and do it well*. That 'thing for the BDFR is taking information from Reddit and putting it on a disk. More advanced dedpulication measures like what you suggest is outside this scope and best left to other tools that have that as their 'thing'.

That being said, your second point should be possible. The folder creation scheme is very flexible. If it is not performing as you desire, please open another issue describing how it does not do what you want and I'll be happy to look, that very much is in the scope of the BDFR.
