### ISSUE TITLE
[FEATURE] - reddit link postings when --skip filetype should create a output file of the posting.

### ISSUE THREAD

**Issue by phhowe17** [aliparlakci/bulk-downloader-for-reddit#752]
- [x ] I am requesting a feature.
- [x ] I am running the latest version of BDfR
- [x ] I have read the [Opening an issue](../../README.md#configuration)

## Description
I'm trying to document postings to a sub-reddit. While most postings are text posting there are occasional link type postings.  Since I don't want to download the content of the link, I have specified --skip MP4, etc.  This results in BDFR ignoring the posting.  It would be nice if BDFR output a file matching the --file-scheme with the content being the link from the posting.  Otherwise there is no record of the posting.

For example this posting (SFW) - https://www.reddit.com/r/auckland/?4295051= is an imgur link. The output should be a file containing the link https://i.imgur.com/LsNCDrg.jpg

**Comment by Serene-Arc** [comment]
This is the wrong use and would be a bad feature if we implemented it. You either want the post content or you don't. If you don't, making a file is counterproductive for every other user. You're explicitly telling the BDFR to ignore these types of links, but you don't actually want them ignored; you just don't want the content.

The features you want are contained in the `archive` command, not the `download` command. `archive` is for when you want to document post information itself, rather than what is linked.

**Comment by phhowe17** [comment]
Archive isn't what I need either, I just want a list of the topics posted to a private reddit with the following information.  I don't need the content, I don't need the comments.

{subreddit}
{date}
{title}
{redditor}
{Postid}

**Comment by Serene-Arc** [comment]
That is the domain of the archiver. You cannot do what you want without using the archiver. You can disable the comment retrieval and ignore the content. But that information is part of the archiver. Additionally, the format it outputs is much more amenable to being analysed. The archiver was designed for data analysis of Reddit.
