### ISSUE TITLE
truncated directory names from {TITLE} [FEATURE]

### ISSUE THREAD

**Issue by siggibiggi** [aliparlakci/bulk-downloader-for-reddit#761]
- [ ] I am requesting a feature.
- [ ] I am running the latest version of BDfR
- [ ] I have read the [Opening an issue](../../README.md#configuration)

## Description

Right now, if I use FOLDER-SCHEME {DATE} {TITLE} {POSTID}, the whole script will stop if it ever encounters a post that exceeds 255 characters (with the date and postid). My current workaround is to just wait for it to break, and then put the offending post in excluded ids, and then rerun the script, but I'll probably improve that system as I want to eventually automate everything. I've thought of various solutions that I know would work, but I think it would be nice if the script automatically truncated the title OR didn't completely stop once it encountered one.

**Comment by Serene-Arc** [comment]
Please read the guide to opening an issue. You haven't done anything that it says so this issue is completely useless. Please [read that](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/development/docs/CONTRIBUTING.md#opening-an-issue) and **follow the instructions**. At the very least you need to provide your operating system and the logs pertaining to the run in question.
