### ISSUE TITLE
input via textfile?

### ISSUE THREAD

**Issue by DankMemeGuy** [aliparlakci/bulk-downloader-for-reddit#82]
Would be nice if I could download a list of users or a list of subreddits instead of manually doing each one.

**Comment by robertb945** [comment]
I made a simple batch file for pulling from a list of multireddits.  Note I store this on my NAS and run it from there, which is why I map a drive.  Very easy to modify for individual subreddits by changing the --mutireddit argument to --subreddit.


::Map drive
net use b: \\[SERVER]\subreddit_rip
b:

::Loop
FOR /F %%m in (b:\MultiReddits.txt) DO (
..\bulk_downloader_for_reddit-1.6.5-windows\bulk-downloader-for-reddit.exe --directory b:\%%m\ --multireddit %%m --user [USERNAME] --sort new --limit 1000 --quit
)

pause

**Comment by aliparlakci** [comment]
You can achieve it via batch scripts.
